#version 450

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main()
{
    // ivec2 texel = ivec2(gl_GlobalInvocationID.xy);

    // // Read input color
    // vec4 inputColor = imageLoad(inputImage, texel);

    // // Perform computation
    // vec4 resultColor = inputColor * 2.0;

    // // Write result to output image
    // imageStore(outputImage, texel, resultColor);
}
